# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/k/Documents/NUVIO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/k/Documents/NUVIO/nuvio-test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/k/Documents/NUVIO/nuvio-test/CMakeFiles /home/k/Documents/NUVIO/nuvio-test//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/k/Documents/NUVIO/nuvio-test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NUVIO

# Build rule for target.
NUVIO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NUVIO
.PHONY : NUVIO

# fast build rule for target.
NUVIO/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/build
.PHONY : NUVIO/fast

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f includes/external/glfw/CMakeFiles/uninstall.dir/build.make includes/external/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f includes/external/glfw/src/CMakeFiles/glfw.dir/build.make includes/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f includes/external/glfw/src/CMakeFiles/update_mappings.dir/build.make includes/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

includes/external/glad/glad.o: includes/external/glad/glad.c.o
.PHONY : includes/external/glad/glad.o

# target to build an object file
includes/external/glad/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/glad/glad.c.o
.PHONY : includes/external/glad/glad.c.o

includes/external/glad/glad.i: includes/external/glad/glad.c.i
.PHONY : includes/external/glad/glad.i

# target to preprocess a source file
includes/external/glad/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/glad/glad.c.i
.PHONY : includes/external/glad/glad.c.i

includes/external/glad/glad.s: includes/external/glad/glad.c.s
.PHONY : includes/external/glad/glad.s

# target to generate assembly for a file
includes/external/glad/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/glad/glad.c.s
.PHONY : includes/external/glad/glad.c.s

includes/external/imgui/backends/imgui_impl_glfw.o: includes/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.o

# target to build an object file
includes/external/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.cpp.o

includes/external/imgui/backends/imgui_impl_glfw.i: includes/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
includes/external/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.cpp.i

includes/external/imgui/backends/imgui_impl_glfw.s: includes/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
includes/external/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : includes/external/imgui/backends/imgui_impl_glfw.cpp.s

includes/external/imgui/backends/imgui_impl_opengl3.o: includes/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
includes/external/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.cpp.o

includes/external/imgui/backends/imgui_impl_opengl3.i: includes/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
includes/external/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.cpp.i

includes/external/imgui/backends/imgui_impl_opengl3.s: includes/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
includes/external/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : includes/external/imgui/backends/imgui_impl_opengl3.cpp.s

includes/external/imgui/imgui.o: includes/external/imgui/imgui.cpp.o
.PHONY : includes/external/imgui/imgui.o

# target to build an object file
includes/external/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui.cpp.o
.PHONY : includes/external/imgui/imgui.cpp.o

includes/external/imgui/imgui.i: includes/external/imgui/imgui.cpp.i
.PHONY : includes/external/imgui/imgui.i

# target to preprocess a source file
includes/external/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui.cpp.i
.PHONY : includes/external/imgui/imgui.cpp.i

includes/external/imgui/imgui.s: includes/external/imgui/imgui.cpp.s
.PHONY : includes/external/imgui/imgui.s

# target to generate assembly for a file
includes/external/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui.cpp.s
.PHONY : includes/external/imgui/imgui.cpp.s

includes/external/imgui/imgui_demo.o: includes/external/imgui/imgui_demo.cpp.o
.PHONY : includes/external/imgui/imgui_demo.o

# target to build an object file
includes/external/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_demo.cpp.o
.PHONY : includes/external/imgui/imgui_demo.cpp.o

includes/external/imgui/imgui_demo.i: includes/external/imgui/imgui_demo.cpp.i
.PHONY : includes/external/imgui/imgui_demo.i

# target to preprocess a source file
includes/external/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_demo.cpp.i
.PHONY : includes/external/imgui/imgui_demo.cpp.i

includes/external/imgui/imgui_demo.s: includes/external/imgui/imgui_demo.cpp.s
.PHONY : includes/external/imgui/imgui_demo.s

# target to generate assembly for a file
includes/external/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_demo.cpp.s
.PHONY : includes/external/imgui/imgui_demo.cpp.s

includes/external/imgui/imgui_draw.o: includes/external/imgui/imgui_draw.cpp.o
.PHONY : includes/external/imgui/imgui_draw.o

# target to build an object file
includes/external/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_draw.cpp.o
.PHONY : includes/external/imgui/imgui_draw.cpp.o

includes/external/imgui/imgui_draw.i: includes/external/imgui/imgui_draw.cpp.i
.PHONY : includes/external/imgui/imgui_draw.i

# target to preprocess a source file
includes/external/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_draw.cpp.i
.PHONY : includes/external/imgui/imgui_draw.cpp.i

includes/external/imgui/imgui_draw.s: includes/external/imgui/imgui_draw.cpp.s
.PHONY : includes/external/imgui/imgui_draw.s

# target to generate assembly for a file
includes/external/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_draw.cpp.s
.PHONY : includes/external/imgui/imgui_draw.cpp.s

includes/external/imgui/imgui_tables.o: includes/external/imgui/imgui_tables.cpp.o
.PHONY : includes/external/imgui/imgui_tables.o

# target to build an object file
includes/external/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_tables.cpp.o
.PHONY : includes/external/imgui/imgui_tables.cpp.o

includes/external/imgui/imgui_tables.i: includes/external/imgui/imgui_tables.cpp.i
.PHONY : includes/external/imgui/imgui_tables.i

# target to preprocess a source file
includes/external/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_tables.cpp.i
.PHONY : includes/external/imgui/imgui_tables.cpp.i

includes/external/imgui/imgui_tables.s: includes/external/imgui/imgui_tables.cpp.s
.PHONY : includes/external/imgui/imgui_tables.s

# target to generate assembly for a file
includes/external/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_tables.cpp.s
.PHONY : includes/external/imgui/imgui_tables.cpp.s

includes/external/imgui/imgui_widgets.o: includes/external/imgui/imgui_widgets.cpp.o
.PHONY : includes/external/imgui/imgui_widgets.o

# target to build an object file
includes/external/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_widgets.cpp.o
.PHONY : includes/external/imgui/imgui_widgets.cpp.o

includes/external/imgui/imgui_widgets.i: includes/external/imgui/imgui_widgets.cpp.i
.PHONY : includes/external/imgui/imgui_widgets.i

# target to preprocess a source file
includes/external/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_widgets.cpp.i
.PHONY : includes/external/imgui/imgui_widgets.cpp.i

includes/external/imgui/imgui_widgets.s: includes/external/imgui/imgui_widgets.cpp.s
.PHONY : includes/external/imgui/imgui_widgets.s

# target to generate assembly for a file
includes/external/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/includes/external/imgui/imgui_widgets.cpp.s
.PHONY : includes/external/imgui/imgui_widgets.cpp.s

src/core/canvas/manager.o: src/core/canvas/manager.cpp.o
.PHONY : src/core/canvas/manager.o

# target to build an object file
src/core/canvas/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/manager.cpp.o
.PHONY : src/core/canvas/manager.cpp.o

src/core/canvas/manager.i: src/core/canvas/manager.cpp.i
.PHONY : src/core/canvas/manager.i

# target to preprocess a source file
src/core/canvas/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/manager.cpp.i
.PHONY : src/core/canvas/manager.cpp.i

src/core/canvas/manager.s: src/core/canvas/manager.cpp.s
.PHONY : src/core/canvas/manager.s

# target to generate assembly for a file
src/core/canvas/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/manager.cpp.s
.PHONY : src/core/canvas/manager.cpp.s

src/core/canvas/shapes/rectangle.o: src/core/canvas/shapes/rectangle.cpp.o
.PHONY : src/core/canvas/shapes/rectangle.o

# target to build an object file
src/core/canvas/shapes/rectangle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/shapes/rectangle.cpp.o
.PHONY : src/core/canvas/shapes/rectangle.cpp.o

src/core/canvas/shapes/rectangle.i: src/core/canvas/shapes/rectangle.cpp.i
.PHONY : src/core/canvas/shapes/rectangle.i

# target to preprocess a source file
src/core/canvas/shapes/rectangle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/shapes/rectangle.cpp.i
.PHONY : src/core/canvas/shapes/rectangle.cpp.i

src/core/canvas/shapes/rectangle.s: src/core/canvas/shapes/rectangle.cpp.s
.PHONY : src/core/canvas/shapes/rectangle.s

# target to generate assembly for a file
src/core/canvas/shapes/rectangle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/canvas/shapes/rectangle.cpp.s
.PHONY : src/core/canvas/shapes/rectangle.cpp.s

src/core/nuvio.o: src/core/nuvio.cpp.o
.PHONY : src/core/nuvio.o

# target to build an object file
src/core/nuvio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/nuvio.cpp.o
.PHONY : src/core/nuvio.cpp.o

src/core/nuvio.i: src/core/nuvio.cpp.i
.PHONY : src/core/nuvio.i

# target to preprocess a source file
src/core/nuvio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/nuvio.cpp.i
.PHONY : src/core/nuvio.cpp.i

src/core/nuvio.s: src/core/nuvio.cpp.s
.PHONY : src/core/nuvio.s

# target to generate assembly for a file
src/core/nuvio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/nuvio.cpp.s
.PHONY : src/core/nuvio.cpp.s

src/core/project/project_manager.o: src/core/project/project_manager.cpp.o
.PHONY : src/core/project/project_manager.o

# target to build an object file
src/core/project/project_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/project_manager.cpp.o
.PHONY : src/core/project/project_manager.cpp.o

src/core/project/project_manager.i: src/core/project/project_manager.cpp.i
.PHONY : src/core/project/project_manager.i

# target to preprocess a source file
src/core/project/project_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/project_manager.cpp.i
.PHONY : src/core/project/project_manager.cpp.i

src/core/project/project_manager.s: src/core/project/project_manager.cpp.s
.PHONY : src/core/project/project_manager.s

# target to generate assembly for a file
src/core/project/project_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/project_manager.cpp.s
.PHONY : src/core/project/project_manager.cpp.s

src/core/project/projects.o: src/core/project/projects.cpp.o
.PHONY : src/core/project/projects.o

# target to build an object file
src/core/project/projects.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/projects.cpp.o
.PHONY : src/core/project/projects.cpp.o

src/core/project/projects.i: src/core/project/projects.cpp.i
.PHONY : src/core/project/projects.i

# target to preprocess a source file
src/core/project/projects.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/projects.cpp.i
.PHONY : src/core/project/projects.cpp.i

src/core/project/projects.s: src/core/project/projects.cpp.s
.PHONY : src/core/project/projects.s

# target to generate assembly for a file
src/core/project/projects.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/project/projects.cpp.s
.PHONY : src/core/project/projects.cpp.s

src/core/shortcut/manager.o: src/core/shortcut/manager.cpp.o
.PHONY : src/core/shortcut/manager.o

# target to build an object file
src/core/shortcut/manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/manager.cpp.o
.PHONY : src/core/shortcut/manager.cpp.o

src/core/shortcut/manager.i: src/core/shortcut/manager.cpp.i
.PHONY : src/core/shortcut/manager.i

# target to preprocess a source file
src/core/shortcut/manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/manager.cpp.i
.PHONY : src/core/shortcut/manager.cpp.i

src/core/shortcut/manager.s: src/core/shortcut/manager.cpp.s
.PHONY : src/core/shortcut/manager.s

# target to generate assembly for a file
src/core/shortcut/manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/manager.cpp.s
.PHONY : src/core/shortcut/manager.cpp.s

src/core/shortcut/registery.o: src/core/shortcut/registery.cpp.o
.PHONY : src/core/shortcut/registery.o

# target to build an object file
src/core/shortcut/registery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/registery.cpp.o
.PHONY : src/core/shortcut/registery.cpp.o

src/core/shortcut/registery.i: src/core/shortcut/registery.cpp.i
.PHONY : src/core/shortcut/registery.i

# target to preprocess a source file
src/core/shortcut/registery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/registery.cpp.i
.PHONY : src/core/shortcut/registery.cpp.i

src/core/shortcut/registery.s: src/core/shortcut/registery.cpp.s
.PHONY : src/core/shortcut/registery.s

# target to generate assembly for a file
src/core/shortcut/registery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/shortcut/registery.cpp.s
.PHONY : src/core/shortcut/registery.cpp.s

src/core/ui/components/registery.o: src/core/ui/components/registery.cpp.o
.PHONY : src/core/ui/components/registery.o

# target to build an object file
src/core/ui/components/registery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/components/registery.cpp.o
.PHONY : src/core/ui/components/registery.cpp.o

src/core/ui/components/registery.i: src/core/ui/components/registery.cpp.i
.PHONY : src/core/ui/components/registery.i

# target to preprocess a source file
src/core/ui/components/registery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/components/registery.cpp.i
.PHONY : src/core/ui/components/registery.cpp.i

src/core/ui/components/registery.s: src/core/ui/components/registery.cpp.s
.PHONY : src/core/ui/components/registery.s

# target to generate assembly for a file
src/core/ui/components/registery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/components/registery.cpp.s
.PHONY : src/core/ui/components/registery.cpp.s

src/core/ui/editor/layers.o: src/core/ui/editor/layers.cpp.o
.PHONY : src/core/ui/editor/layers.o

# target to build an object file
src/core/ui/editor/layers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/layers.cpp.o
.PHONY : src/core/ui/editor/layers.cpp.o

src/core/ui/editor/layers.i: src/core/ui/editor/layers.cpp.i
.PHONY : src/core/ui/editor/layers.i

# target to preprocess a source file
src/core/ui/editor/layers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/layers.cpp.i
.PHONY : src/core/ui/editor/layers.cpp.i

src/core/ui/editor/layers.s: src/core/ui/editor/layers.cpp.s
.PHONY : src/core/ui/editor/layers.s

# target to generate assembly for a file
src/core/ui/editor/layers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/layers.cpp.s
.PHONY : src/core/ui/editor/layers.cpp.s

src/core/ui/editor/navbar.o: src/core/ui/editor/navbar.cpp.o
.PHONY : src/core/ui/editor/navbar.o

# target to build an object file
src/core/ui/editor/navbar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/navbar.cpp.o
.PHONY : src/core/ui/editor/navbar.cpp.o

src/core/ui/editor/navbar.i: src/core/ui/editor/navbar.cpp.i
.PHONY : src/core/ui/editor/navbar.i

# target to preprocess a source file
src/core/ui/editor/navbar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/navbar.cpp.i
.PHONY : src/core/ui/editor/navbar.cpp.i

src/core/ui/editor/navbar.s: src/core/ui/editor/navbar.cpp.s
.PHONY : src/core/ui/editor/navbar.s

# target to generate assembly for a file
src/core/ui/editor/navbar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/navbar.cpp.s
.PHONY : src/core/ui/editor/navbar.cpp.s

src/core/ui/editor/sidebar.o: src/core/ui/editor/sidebar.cpp.o
.PHONY : src/core/ui/editor/sidebar.o

# target to build an object file
src/core/ui/editor/sidebar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/sidebar.cpp.o
.PHONY : src/core/ui/editor/sidebar.cpp.o

src/core/ui/editor/sidebar.i: src/core/ui/editor/sidebar.cpp.i
.PHONY : src/core/ui/editor/sidebar.i

# target to preprocess a source file
src/core/ui/editor/sidebar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/sidebar.cpp.i
.PHONY : src/core/ui/editor/sidebar.cpp.i

src/core/ui/editor/sidebar.s: src/core/ui/editor/sidebar.cpp.s
.PHONY : src/core/ui/editor/sidebar.s

# target to generate assembly for a file
src/core/ui/editor/sidebar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/sidebar.cpp.s
.PHONY : src/core/ui/editor/sidebar.cpp.s

src/core/ui/editor/viewport.o: src/core/ui/editor/viewport.cpp.o
.PHONY : src/core/ui/editor/viewport.o

# target to build an object file
src/core/ui/editor/viewport.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/viewport.cpp.o
.PHONY : src/core/ui/editor/viewport.cpp.o

src/core/ui/editor/viewport.i: src/core/ui/editor/viewport.cpp.i
.PHONY : src/core/ui/editor/viewport.i

# target to preprocess a source file
src/core/ui/editor/viewport.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/viewport.cpp.i
.PHONY : src/core/ui/editor/viewport.cpp.i

src/core/ui/editor/viewport.s: src/core/ui/editor/viewport.cpp.s
.PHONY : src/core/ui/editor/viewport.s

# target to generate assembly for a file
src/core/ui/editor/viewport.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/editor/viewport.cpp.s
.PHONY : src/core/ui/editor/viewport.cpp.s

src/core/ui/test_comp.o: src/core/ui/test_comp.cpp.o
.PHONY : src/core/ui/test_comp.o

# target to build an object file
src/core/ui/test_comp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/test_comp.cpp.o
.PHONY : src/core/ui/test_comp.cpp.o

src/core/ui/test_comp.i: src/core/ui/test_comp.cpp.i
.PHONY : src/core/ui/test_comp.i

# target to preprocess a source file
src/core/ui/test_comp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/test_comp.cpp.i
.PHONY : src/core/ui/test_comp.cpp.i

src/core/ui/test_comp.s: src/core/ui/test_comp.cpp.s
.PHONY : src/core/ui/test_comp.s

# target to generate assembly for a file
src/core/ui/test_comp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/test_comp.cpp.s
.PHONY : src/core/ui/test_comp.cpp.s

src/core/ui/theme.o: src/core/ui/theme.cpp.o
.PHONY : src/core/ui/theme.o

# target to build an object file
src/core/ui/theme.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/theme.cpp.o
.PHONY : src/core/ui/theme.cpp.o

src/core/ui/theme.i: src/core/ui/theme.cpp.i
.PHONY : src/core/ui/theme.i

# target to preprocess a source file
src/core/ui/theme.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/theme.cpp.i
.PHONY : src/core/ui/theme.cpp.i

src/core/ui/theme.s: src/core/ui/theme.cpp.s
.PHONY : src/core/ui/theme.s

# target to generate assembly for a file
src/core/ui/theme.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/theme.cpp.s
.PHONY : src/core/ui/theme.cpp.s

src/core/ui/ui.o: src/core/ui/ui.cpp.o
.PHONY : src/core/ui/ui.o

# target to build an object file
src/core/ui/ui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/ui.cpp.o
.PHONY : src/core/ui/ui.cpp.o

src/core/ui/ui.i: src/core/ui/ui.cpp.i
.PHONY : src/core/ui/ui.i

# target to preprocess a source file
src/core/ui/ui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/ui.cpp.i
.PHONY : src/core/ui/ui.cpp.i

src/core/ui/ui.s: src/core/ui/ui.cpp.s
.PHONY : src/core/ui/ui.s

# target to generate assembly for a file
src/core/ui/ui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/ui/ui.cpp.s
.PHONY : src/core/ui/ui.cpp.s

src/core/window/window_manager.o: src/core/window/window_manager.cpp.o
.PHONY : src/core/window/window_manager.o

# target to build an object file
src/core/window/window_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/window/window_manager.cpp.o
.PHONY : src/core/window/window_manager.cpp.o

src/core/window/window_manager.i: src/core/window/window_manager.cpp.i
.PHONY : src/core/window/window_manager.i

# target to preprocess a source file
src/core/window/window_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/window/window_manager.cpp.i
.PHONY : src/core/window/window_manager.cpp.i

src/core/window/window_manager.s: src/core/window/window_manager.cpp.s
.PHONY : src/core/window/window_manager.s

# target to generate assembly for a file
src/core/window/window_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/core/window/window_manager.cpp.s
.PHONY : src/core/window/window_manager.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/NUVIO.dir/build.make CMakeFiles/NUVIO.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... NUVIO"
	@echo "... glfw"
	@echo "... includes/external/glad/glad.o"
	@echo "... includes/external/glad/glad.i"
	@echo "... includes/external/glad/glad.s"
	@echo "... includes/external/imgui/backends/imgui_impl_glfw.o"
	@echo "... includes/external/imgui/backends/imgui_impl_glfw.i"
	@echo "... includes/external/imgui/backends/imgui_impl_glfw.s"
	@echo "... includes/external/imgui/backends/imgui_impl_opengl3.o"
	@echo "... includes/external/imgui/backends/imgui_impl_opengl3.i"
	@echo "... includes/external/imgui/backends/imgui_impl_opengl3.s"
	@echo "... includes/external/imgui/imgui.o"
	@echo "... includes/external/imgui/imgui.i"
	@echo "... includes/external/imgui/imgui.s"
	@echo "... includes/external/imgui/imgui_demo.o"
	@echo "... includes/external/imgui/imgui_demo.i"
	@echo "... includes/external/imgui/imgui_demo.s"
	@echo "... includes/external/imgui/imgui_draw.o"
	@echo "... includes/external/imgui/imgui_draw.i"
	@echo "... includes/external/imgui/imgui_draw.s"
	@echo "... includes/external/imgui/imgui_tables.o"
	@echo "... includes/external/imgui/imgui_tables.i"
	@echo "... includes/external/imgui/imgui_tables.s"
	@echo "... includes/external/imgui/imgui_widgets.o"
	@echo "... includes/external/imgui/imgui_widgets.i"
	@echo "... includes/external/imgui/imgui_widgets.s"
	@echo "... src/core/canvas/manager.o"
	@echo "... src/core/canvas/manager.i"
	@echo "... src/core/canvas/manager.s"
	@echo "... src/core/canvas/shapes/rectangle.o"
	@echo "... src/core/canvas/shapes/rectangle.i"
	@echo "... src/core/canvas/shapes/rectangle.s"
	@echo "... src/core/nuvio.o"
	@echo "... src/core/nuvio.i"
	@echo "... src/core/nuvio.s"
	@echo "... src/core/project/project_manager.o"
	@echo "... src/core/project/project_manager.i"
	@echo "... src/core/project/project_manager.s"
	@echo "... src/core/project/projects.o"
	@echo "... src/core/project/projects.i"
	@echo "... src/core/project/projects.s"
	@echo "... src/core/shortcut/manager.o"
	@echo "... src/core/shortcut/manager.i"
	@echo "... src/core/shortcut/manager.s"
	@echo "... src/core/shortcut/registery.o"
	@echo "... src/core/shortcut/registery.i"
	@echo "... src/core/shortcut/registery.s"
	@echo "... src/core/ui/components/registery.o"
	@echo "... src/core/ui/components/registery.i"
	@echo "... src/core/ui/components/registery.s"
	@echo "... src/core/ui/editor/layers.o"
	@echo "... src/core/ui/editor/layers.i"
	@echo "... src/core/ui/editor/layers.s"
	@echo "... src/core/ui/editor/navbar.o"
	@echo "... src/core/ui/editor/navbar.i"
	@echo "... src/core/ui/editor/navbar.s"
	@echo "... src/core/ui/editor/sidebar.o"
	@echo "... src/core/ui/editor/sidebar.i"
	@echo "... src/core/ui/editor/sidebar.s"
	@echo "... src/core/ui/editor/viewport.o"
	@echo "... src/core/ui/editor/viewport.i"
	@echo "... src/core/ui/editor/viewport.s"
	@echo "... src/core/ui/test_comp.o"
	@echo "... src/core/ui/test_comp.i"
	@echo "... src/core/ui/test_comp.s"
	@echo "... src/core/ui/theme.o"
	@echo "... src/core/ui/theme.i"
	@echo "... src/core/ui/theme.s"
	@echo "... src/core/ui/ui.o"
	@echo "... src/core/ui/ui.i"
	@echo "... src/core/ui/ui.s"
	@echo "... src/core/window/window_manager.o"
	@echo "... src/core/window/window_manager.i"
	@echo "... src/core/window/window_manager.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

